{
 "title": "HStream Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "host",
    "query": {
     "query": "label_values(up{group=\"node_exporter\"}, instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Stream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AppendSpeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_stream_append_in_bytes{server_host=~\"$host\"}[$interval])) by(server_host)",
     "legendFormat": "{{server_host}}-append"
    },
    {
     "expr": "sum(rate(hstream_exporter_stream_append_in_bytes[$interval]))",
     "legendFormat": "total-append-speed"
    }
   ]
  },
  {
   "title": "AppendQPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_stream_append_total{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-qps"
    },
    {
     "expr": "sum(rate(hstream_exporter_stream_append_total[$interval]))",
     "legendFormat": "total-qps"
    }
   ]
  },
  {
   "title": "AppendRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hstream_exporter_stream_append_latency{server_host=~\"$host\"}",
     "legendFormat": "{{server_host}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "FailedAppendPersentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_stream_append_failed{server_host=~\"$host\"}[$interval])) by (server_host) / sum(rate(hstream_exporter_stream_append_total{server_host=~\"$host\"}[$interval])) by (server_host) * 100",
     "legendFormat": "{{server_host}}"
    },
    {
     "expr": "sum(rate(hstream_exporter_stream_append_failed[$interval])) / sum(rate(hstream_exporter_stream_append_total[$interval])) * 100",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Subscription Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "SubSendSpeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_subscription_send_out_bytes{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-send-speed"
    },
    {
     "expr": "sum(rate(hstream_exporter_subscription_send_out_bytes[$interval]))",
     "legendFormat": "total-send-speed"
    }
   ]
  },
  {
   "title": "SubAck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_subscription_received_acks{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-ack"
    },
    {
     "expr": "sum(rate(hstream_exporter_subscription_received_acks[$interval]))",
     "legendFormat": "total-ack"
    }
   ]
  },
  {
   "title": "SubscriptionRequestQPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_subscription_request_messages{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-sub-req"
    },
    {
     "expr": "sum(rate(hstream_exporter_subscription_request_messages[$interval]))",
     "legendFormat": "total-sub-req"
    }
   ]
  },
  {
   "title": "SubscriptionResponsetQPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_subscription_response_messages{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-sub-response"
    },
    {
     "expr": "sum(rate(hstream_exporter_subscription_response_messages[$interval]))",
     "legendFormat": "total-sub-response"
    }
   ]
  },
  {
   "title": "SubResend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(hstream_exporter_subscription_resend_records{server_host=~\"$host\"}[$interval])) by (server_host)",
     "legendFormat": "{{server_host}}-sub-resend"
    },
    {
     "expr": "sum(rate(hstream_exporter_subscription_resend_records[$interval]))",
     "legendFormat": "total-resend"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Node CPU Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\"}[$interval])) by (instance)) * 100",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", mode=\"system\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}-system"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", mode=\"user\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}-user"
    }
   ]
  },
  {
   "title": "Node Memory Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{instance=~\"$host\"}) by(instance) / sum(node_memory_MemTotal_bytes{instance=~\"$host\"}) by(instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_network_receive_bytes_total{instance=~\"$host\", device=~\"eth.*\"}[$interval]))",
     "legendFormat": "{{instance}}-receive"
    },
    {
     "expr": "sum by(instance) (irate(node_network_transmit_bytes_total{instance=~\"$host\", device=~\"eth.*\"}[$interval]))",
     "legendFormat": "{{instance}}-transmit"
    }
   ]
  },
  {
   "title": "Node Disk Read Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$host\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$host\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-write"
    }
   ]
  }
 ]
}