kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  # 根据实际情况修改sc
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi